openapi: 3.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: Requests should pass a token header.
paths:
  /items:
    summary: Create new attachemt
    x-swagger-router-controller: items
    post:
      tags:
      - "items"
      security:
        - bearerAuth: []
      description: Create new item
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: content
          type: string
          in: formData
          required: true
        - name: status
          type: string
          enum:
            - "in_progress"
            - "done"
          in: formData
          required: true
        - name: taskId
          type: string
          in: formData
          required: true
      operationId: create
      responses:
        200:
          description: New item created
    delete:
      tags:
      - "items"
      security:
        - bearerAuth: []
      description: Delete multiple items
      comsumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: itemIds
          type: string
          required: true
          description: Item Ids
          schema:
            $ref: '#/definitions/MessageItemBulkDelete'
      operationId: delete
      responses:
        200:
          description: Deleted Items
    put:
      tags:
      - "items"
      security:
        - bearerAuth: []
      description: Update multiple items
      parameters:
        - in: body
          name: itemIds
          type: string
          required: true
          description: Item Ids
          schema:
            $ref: '#/definitions/MessageItemBulkUpdate'
      operationId: view
      responses:
        200:
          description: Update multiple items
  /items/{id}:
    summary: Specific item
    x-swagger-router-controller: items
    get:
      tags:
      - "items"
      security:
        - bearerAuth: []
      description: Show Item
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Item Id
      operationId: view
      responses:
        200:
          description: Show item
    put:
      tags:
      - "items"
      security:
        - bearerAuth: []
      description: Update item
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Item Id
        - name: content
          required: true
          type: string
          in: formData
          description: Item content
        - name: status
          type: string
          required: true
          in: formData
          description: Item status
      operationId: delete
      responses:
        200:
          description: Update item
definitions:
  Item:
    type: "object"
    properties:
      id:
        type: "string"
        format: "UUID"
      content:
        type: "string"
      status:
        type: "string"
        description: "Task Status"
        enum:
        - "in_progress"
        - "done"
      taskId:
        type: "string"
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      deletedAt:
        type: string
        format: date-time
    xml:
      name: "Item"

  MessageItemBulkDelete:
    type: object
    properties:
      itemIds:
        type: array
  MessageItemBulkUpdate:
    type: object
    properties:
      itemIds:
        type: array
      content:
        type: string
      status:
        type: string
        enum:
          - "in_progress"
          - "done"