openapi: 3.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: Requests should pass a token header.
tags:
- name: "authentication"
  description: "Operations about authentication"
- name: "tasks"
  description: "Operations about tasks"
- name: "items"
  description: "Operations about items"
- name: "users"
  description: "Operations about user"
paths:
  /tasks:
    summary: Get all tasks
    x-swagger-router-controller: tasks
    get:
      tags:
      - "tasks"
      security:
        - bearerAuth: []
      description: Get all tasks
      parameters:
        - in: query
          name: syncedAt
          schema:
            type: datetime
          description: Time to sync tasks
        - in: query
          name: page
          schema:
            type: integer
          description: The page number
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of items to return
        - in: query
          name: date
          schema:
            type: date
          description: date
      operationId: getTasks
      responses:
        200:
          description: All tasks
    post:
      tags:
      - "tasks"
      security:
        - bearerAuth: []
      description: Create new task
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: name
          type: string
          in: formData
          required: true
        - name: content
          required: true
          in: formData
          type: string
        - name: deadline
          required: true
          in: formData
          type: string
        - name: status
          required: true
          in: formData
          type: string
      operationId: create
      responses:
        200:
          description: New task
    delete:
      tags:
      - "tasks"
      security:
        - bearerAuth: []
      description: delete multiple tasks
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: taskIds
          type: string
          in: body
          schema:
              $ref: '#/definitions/MessageTaskBulkDelete'
      operationId: delete multiple
      responses:
        200:
          description: Deleted tasks
    put:
      tags:
      - "tasks"
      security:
        - bearerAuth: []
      description: Update multiple tasks
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: taskIds
          type: string
          in: body
          schema:
            $ref: '#/definitions/MessageTaskBulkUpdate'
      operationId: update multiple
      responses:
        200:
          description: Update multiple tasks
  /tasks/{id}:
    summary: Get task detail
    x-swagger-router-controller: tasks
    get:
      tags:
      - "tasks"
      security:
        - bearerAuth: []
      description: Get task detail
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Task Id
      operationId: getTaskById
      responses:
        200:
          description: Get task detail
    delete:
      tags:
      - "tasks"
      security:
        - bearerAuth: []
      description: delete task
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Task Id
      operationId: deleteTask
      responses:
        200:
          description: Delete task
    put:
      tags:
      - "tasks"
      security:
        - bearerAuth: []
      description: Update task
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Task Id
        - name: status
          type: string
          in: formData
          required: true
        - name: name
          type: string
          in: formData
          required: true
        - name: content
          type: string
          in: formData
          required: true
        - name: deadline
          type: string
          in: formData
          required: true
      operationId: updateTask
      responses:
        200:
          description: Update task
  /tasks/trashed:
    summary: All trashed tasks
    x-swagger-router-controller: tasks
    get:
      tags:
      - "tasks"
      security:
        - bearerAuth: []
      description: Get all trashed tasks
      parameters:
        - in: query
          name: page
          type: integer
          required: true
        - in: query
          name: limit
          type: integer
          required: true
      operationId: getAlbumAttachments
      responses:
        200:
          description: Get all trashed tasks
  /tasks/restore:
    summary: Restore trashed tasks
    x-swagger-router-controller: tasks
    put:
      tags:
      - "tasks"
      security:
        - bearerAuth: []
      description: restore trashed tasks
      consumes:
        - application/json
      parameters:
        - in: body
          name: taskIds
          type: string
          required: true
          description: Task Ids
          schema:
            $ref: '#/definitions/MessageTaskBulkRestore'
      operationId: locking
      responses:
        200:
          description: restored trashed tasks

definitions:
  Task:
    type: "object"
    properties:
      id:
        type: "string"
        format: "UUID"
      name:
        type: "string"
      content:
        type: "string"
      deadline:
        type: "datetime"
      status:
        type: "string"
        description: "Task Status"
        enum:
        - "in_progress"
        - "done"
      userId:
        type: "string"
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      deletedAt:
        type: string
        format: date-time
    xml:
      name: "Task"
  MessageTaskBulkDelete:
    type: object
    properties:
      taskIds:
        type: array
  MessageTaskBulkUpdate:
    type: object
    properties:
      taskIds:
        type: array
      name:
        type: string
      content:
        type: string
      deadline:
        type: string
      status:
        type: string
        enum:
        - "in_progress"
        - "done"
  MessageTaskBulkRestore:
    type: object
    properties:
      taskIds:
        type: array