openapi: 3.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: Requests should pass a token header.